services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db:/db
      - ./backend/data:/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: false
